language: python
python:
  - "3.4"
# command to install dependencies
install: 
    - git clone https://github.com/stefanoborini/vaitk.git vaitk
    - cd vaitk && python setup.py install
    - python setup.py install
# command to run tests
script: nosetests
